GET http://localhost:3000/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiSmltIiwiaWF0IjoxNjA1MTMxMTczfQ.ukVzG4fr7h9yp-w1r21fqt9o79K_M2ghKYLPn9xJOXc

###

POST http://localhost:3000/login
Content-Type: application/json

{
    "username": "Jim"
}