

### This GET authenticates and displays the content of the JWT token created by the initial JWT or the JWT refresh token

GET http://localhost:3000/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiS3lsZSIsImlhdCI6MTYwNjA0MDMzOH0.AuiC-W6D16fdmkHQlCSxYFdJJWx1DHprMHO6fYp3T1c

### This GET is used to display all cookies created

GET http://localhost:3000


### This GET is used to clear all cookies created

GET http://localhost:3000/clear

### This DELETE looks to prevent the JWT refresh token from creating addition access tokens

DELETE http://localhost:3000/logout
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiS3lsZSIsImlhdCI6MTYwNjAyNjMzNX0.uwPy9uplbtCpg3kWix6mOPnTzDQhc1I2jruCGGmR34c"

}

### Once the JWT refresh token is entered into "token", you can generate additional time-based access tokens as a cookie

POST http://localhost:3000/refresh
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiS3lsZSIsImlhdCI6MTYwNjAyODYwOH0._fHTFeYf9Z7H1HbxGu-D-D-peodqSUj5_ladLCX87RI"
}

### This POST request is used to generate the inital JWT access token and JWT refresh access token as a cookie

POST http://localhost:3000/survey
Content-Type: application/json

{
    "username": "Kyle"
}

### This POST is used to show recipe response

POST http://localhost:3000/recipe
